repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
      exclude: >
        (?x)^(
            ^{{.*}}.*\.yaml$|
            ^.*/templates/.*$
        )
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17
  hooks:
    - id: helmlint
